name: Deploy MedSpaSync Pro

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install frontend dependencies
        run: npm install --prefix medspasync-frontend
      - name: Build frontend
        run: npm run build --prefix medspasync-frontend
      - name: Install backend dependencies
        run: npm install --prefix medspasync-backend
      - name: Build backend (if applicable)
        run: echo "No build step for backend" # Replace with build command if needed
      # - name: Deploy to Vercel
      #   uses: amondnet/vercel-action@v25
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
      #     working-directory: medspasync-frontend
      # - name: Deploy to Railway
      #   run: echo "Add Railway deployment step here"
      #   # See Railway docs for GitHub Actions integration 