name: MedSpaSync Marketing CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: medspasync-marketing/package-lock.json

    - name: Install dependencies
      run: npm install
      working-directory: ./medspasync-marketing

    - name: Run linting
      run: npm run lint
      working-directory: ./medspasync-marketing

    - name: Run tests
      run: npm run test
      working-directory: ./medspasync-marketing

    - name: Build project
      run: npm run build
      working-directory: ./medspasync-marketing
