# netlify.toml - MedSpaSync Pro Marketing Site
# Corrected configuration for professional medical spa platform

[build]
  command = "npm run build"
  publish = "dist"
  
  [build.environment]
    NODE_VERSION = "18.19.1"
    NPM_VERSION = "10.2.4"
    NODE_ENV = "production"
    GENERATE_SOURCEMAP = "false"
    VITE_PLATFORM_NAME = "MedSpaSync Pro"
    VITE_CONTACT_EMAIL = "support@medspasyncpro.com"

# Build processing configuration
[build.processing]
  skip_processing = false

  [build.processing.css]
    bundle = true
    minify = true

  [build.processing.js]
    bundle = true
    minify = true

  [build.processing.html]
    pretty_urls = true

  [build.processing.images]
    compress = true

# Redirect rules for medical spa platform
[[redirects]]
  # Legacy URL redirects
  from = "/reconciliation"
  to = "/features"
  status = 301

[[redirects]]
  # Demo access shortcuts
  from = "/try"
  to = "https://demo.medspasyncpro.com"
  status = 302

[[redirects]]
  # App platform redirect
  from = "/app"
  to = "https://demo.medspasyncpro.com"
  status = 302

[[redirects]]
  # API redirects to backend
  from = "/api/*"
  to = "https://api.medspasyncpro.com/:splat"
  status = 200

[[redirects]]
  # Contact form submission
  from = "/contact-submit"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  # SPA fallback - MUST be last rule
  from = "/*"
  to = "/index.html"
  status = 200

# Security and performance headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers for medical spa compliance
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # Content Security Policy
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data: https://status.medspasyncpro.com; connect-src 'self' https://api.medspasyncpro.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'"
    
    # Default caching for HTML
    Cache-Control = "public, max-age=0, must-revalidate"

# Static asset optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.{png,jpg,jpeg,gif,svg,webp,avif}"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Vary = "Accept"

[[headers]]
  for = "*.{css,js}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "text/plain"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Function configuration for contact forms
[functions]
  directory = "netlify/functions"

# Context-specific configurations
[context.production]
  command = "npm run build"
  
  [context.production.environment]
    NODE_ENV = "production"
    VITE_GA_TRACKING_ID = "G-XXXXXXXXXX"
    VITE_HOTJAR_ID = "XXXXXXX"

[context.deploy-preview]
  command = "npm run build"
  
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    VITE_ROBOTS_NOINDEX = "true"

[context.branch-deploy]
  command = "npm run build"