[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"

[env]
VITE_API_URL = "https://api.medspasyncpro.com"
REACT_APP_API_BASE = "https://api.medspasyncpro.com/api"
NODE_ENV = "production"
