[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"

[variables]
PORT = "3000"
VITE_BASE_PATH = "/"
VITE_API_BASE_URL = "https://api.medspasyncpro.com"
