# AI Kingdom Monitoring Configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # MedSpaSync Backend API
  - job_name: 'medspasync-backend'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    scheme: http

  # MedSpaSync Frontend (if exposing metrics)
  - job_name: 'medspasync-frontend'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true
    scheme: http

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['localhost:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true
    scheme: http

  # PostgreSQL Metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['localhost:9187']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true
    scheme: http

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true
    scheme: http

  # Alert Manager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 5s
    honor_labels: true
    scheme: http

# Alerting Rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording Rules (for pre-computed metrics)
rule_files:
  - "medspasync-rules.yml" 